sudo: required
language: node_js
node_js:
  - "4.8"
  - "4.6"
  - "4.4"
  - "4.2.2"
  - "4.2"
  - "0.12"
cache:
  - apt
sources:
  - trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-cache search libboost
  - sudo apt-get install -y libboost-thread1.48.0 libboost-system1.48.0
  - npm install -g npm@2.x
  - npm install express
  - npm install supervisor -g
  - npm install nconf --save
  - npm install syno-upstarter --save
  - npm install -g gulp 
  - npm install -g grunt-cli
  - npm install gulp-jshint gulp-concat gulp-uglify gulp-rename --save-dev 
  - npm install underscore moment path request body-parser basic-auth errorhandler sync-request morgan http method-override
  - npm install
  - mkdir domoticz
  - cd domoticz
  - wget https://releases.domoticz.com/releases/beta/domoticz_linux_x86_64.tgz
  - tar xvzf domoticz_linux_x86_64.tgz
  - wget http://www.e-nef.com/domoticz/mdah/domoticz.db
  - cd ..
notifications:
  recipients:
    - domoticz@e-nef.com
  slack: 
    mydomoathome:dYICWN8iWCZFrtlZCyMIVwtw
  email:
#    on_success: change
    on_failure: always
#env:
#after_failure: "cat /home/travis/builds/npm-debug.log"
install: npm i
before_script: 
  - npm i
  - domoticz/domoticz &
  - node mdah.js &
script: "grunt"
